Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPagesize: 10
  MaxPageSize: 100
  RequestTimeout: 60  #请求超时(秒)
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 #MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: Sky147258369?
  Host: 127.0.0.1
  Port: 3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 10
JWT:
  Secret: doifusd
  Issuer: sky
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 456
  UserName: 812517142@qq.com
  Password: Sky147258369$
  IsSSL: true
  From: 812517142.@qq.com
  TO: 
    - doifusd@163.com
Tracer:
  ServiceName: blog
  AgentHostPort: 127.0.0.1:6831









